### ISSUE TITLE
Generate HTML is failing

### ISSUE THREAD

**Issue by jnylen** [xmltv-se/vind#152]
```
2020-05-10 18:50:05.095 [error] TaskBunny - Elixir.Main.Workers.Recurring.GenerateHTML failed for an exception.

Exception:
%FunctionClauseError{
  args: nil,
  arity: 1,
  clauses: nil,
  function: :file_list,
  kind: nil,
  module: Main.Workers.Recurring.GenerateHTML
}

Payload:
  %{}

History:
  - Failed count: 11
  - Reject: true

Worker:
  - Queue: task_bunny.recurring
  - Concurrency: 30
  - PID: #PID<0.6040.0>


Stacktrace:
    (main 0.1.0) lib/main/workers/recurring/generate_html.ex:63: Main.Workers.Recurring.GenerateHTML.file_list("premium_xmltv")
    (main 0.1.0) lib/main/workers/recurring/generate_html.ex:26: Main.Workers.Recurring.GenerateHTML.perform/1
    (task_bunny 0.3.4) lib/task_bunny/job_runner.ex:65: TaskBunny.JobRunner.run_job/2
    (task_bunny 0.3.4) lib/task_bunny/job_runner.ex:48: anonymous fn/5 in TaskBunny.JobRunner.invoke/3
```

**Comment by jnylen** [comment]
Fixed in #160
